-- Remove columns from products table that will be moved to variants
alter table products
    drop column sizes,
    drop column price,
    drop column quantity,
    drop column price_id;

-- Create product_variants table
create table product_variants (
    id bigint primary key generated by default as identity,
    product_id bigint references products(id) on delete cascade,
    size text,
    color text,
    price numeric not null,
    quantity integer not null default 0,
    price_id text, -- Stripe/payment processor price ID
    sku text, -- Stock keeping unit
    created_at timestamptz default now()
);

-- Add constraints
alter table product_variants
    add constraint product_variants_unique_combination
    unique (product_id, size, color);

-- Create indexes for better query performance
create index product_variants_product_id_idx on product_variants(product_id);
create index product_variants_size_idx on product_variants(size);
create index product_variants_color_idx on product_variants(color);
create index product_variants_price_idx on product_variants(price);
create index product_variants_sku_idx on product_variants(sku);

-- Enable RLS on product_variants table
alter table product_variants enable row level security;

-- Create policies for product_variants table
create policy "Allow public read access to product variants"
    on product_variants for select
    to public
    using (true);

create policy "Allow authenticated users to modify product variants"
    on product_variants for all
    to authenticated
    using (true)
    with check (true);

-- Modify stock_notifications to reference variants instead of products
alter table stock_notifications
    add column variant_id bigint references product_variants(id) on delete cascade,
    drop constraint stock_notifications_product_id_fkey,
    drop column product_id;

-- Update unique constraint for stock notifications
drop index if exists stock_notifications_unique_idx;
create unique index stock_notifications_unique_idx 
    on stock_notifications(variant_id, email) 
    where is_notified = false;

-- Create index for variant_id in stock_notifications
create index stock_notifications_variant_id_idx on stock_notifications(variant_id); 