create table products (
    id bigint primary key generated by default as identity,
    name text not null,
    description text,
    price numeric not null,
    quantity integer not null default 0,
    is_preorder boolean not null default false,
    is_notify boolean not null default false,
    sizes text[], -- Array of text for sizes
    price_id text, -- For payment processor reference
    created_at timestamptz default now()
);

-- Create indexes for better query performance
create index products_created_at_idx on products(created_at);
create index products_price_idx on products(price);

-- Create product_images table
create table product_images (
    id bigint primary key generated by default as identity,
    product_id bigint references products(id) on delete cascade,
    image_url text not null,
    is_main boolean default false,
    sort_order integer default 0,
    created_at timestamptz default now()
);

-- Create indexes for better query performance
create index product_images_product_id_idx on product_images(product_id);
create index product_images_is_main_idx on product_images(is_main);
create index product_images_sort_order_idx on product_images(sort_order);

-- Add constraint to ensure only one main image per product
create unique index product_images_main_image_idx 
    on product_images(product_id) 
    where is_main = true;

-- Create storage bucket for product images
insert into storage.buckets (id, name, public)
values ('images', 'images', true);

-- Create storage policy to allow public access to images
create policy "Public Access"
on storage.objects for select
to public
using ( bucket_id = 'images' );

-- Create storage policy to allow authenticated users to upload images
create policy "Authenticated users can upload images"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'images' );

-- Create storage policy to allow authenticated users to update their images
create policy "Authenticated users can update images"
on storage.objects for update
to authenticated
using ( bucket_id = 'images' );

-- Create storage policy to allow authenticated users to delete their images
create policy "Authenticated users can delete images"
on storage.objects for delete
to authenticated
using ( bucket_id = 'images' );

-- Create stock notifications table
create table stock_notifications (
    id bigint primary key generated by default as identity,
    product_id bigint references products(id) on delete cascade,
    email text not null,
    is_notified boolean default false,
    created_at timestamptz default now()
);

-- Create indexes for better query performance
create index stock_notifications_product_id_idx on stock_notifications(product_id);
create index stock_notifications_email_idx on stock_notifications(email);
create index stock_notifications_is_notified_idx on stock_notifications(is_notified);

-- Create unique constraint to prevent duplicate notifications
create unique index stock_notifications_unique_idx 
    on stock_notifications(product_id, email) 
    where is_notified = false;
